### ISSUE TITLE
switch(remainder) case 2 & 3 in 32-bit appears to not modify hash

### ISSUE THREAD

**Issue by awsles** [karanlyons/murmurHash3.js#10]
In the JavaScript function [x86.hash32](https://github.com/karanlyons/murmurHash3.js/blob/master/src/index.ts), the **switch(**_remainder_**)** statement at line 237 modifies **k1** in  each case. However, for case 3 and 2, **h** does _not_ appear to be modified by **k1** before exiting the function (in case 1, it is clearly modified).

What am I missing?

**Comment by karanlyons** [comment]
switch cases implicitly fall through, they’re basically just gotos.
