### ISSUE TITLE
Output matches C++ reference implementation only for regular ASCII inputs

### ISSUE THREAD

**Issue by cimi** [karanlyons/murmurHash3.js#4]
👋 Hi there!

First of all, thank you for your work! I've been successfully using this library in production for a couple of years and it's been very useful.

Recently we've started using MurmurHash3 on other platforms - we need the results to match and noticed discrepancies between the output of the JS version and the other platforms when the input had characters that were not regular ASCII (i.e. `charCodeAt` is not between 0 and 127).

This is because in some places the code does `key.charCodeAt(i) & 0xff` and in other places just `key.charCodeAt(i)`. The byte representation for regular ASCII characters is identical with the character code so for e.g. alphanumeric input this doesn't matter. If the input characters are outside this range, the results start to diverge with the reference implementation.

All the three variants have this problem. For example, here's the output for the x86 32bit version:

| Input | C++ result (reference) | murmurhash3js result |
| ---- | ---- | ---- |
| 'My hovercraft is full of eels.' | 2953494853 | 2953494853 |
| 'My 🚀 is full of 🦎.' | 1818098979 | 2899624186 |
| '吉 星 高 照' | 3435142074 | 4163339522 |

The string was utf-8 encoded before being passed in to the C++ reference as that expects bytes. I think it's fair to expect people using other implementations that ask for bytes will do this.

I decided to change the signature of the function to make it expect bytes. I checked my implementation along with a few others against the reference C++ implementation. You can read more about it and [try out an interactive version of the comparison here](https://cimi.io/murmurhash3js-revisited/).

Since I needed a quick release and the new signature is a major/breaking change compared to this implementation, I published my own version of the library as `murmurhash3js-revisited`. I tried to keep all attribution, but if you have any concerns please let me know!

This issue was copied from pid/murmurhash3js#3 - I was using that version of murmurhash but since it was forked from this one, looking at the code this seems to have the same problem.

Cheers!

**Comment by karanlyons** [comment]
Yikes. This is a very good catch, and something I definitely should have thought about when I first put this together. I think at the time `TextEncoder` didn’t exist, and either `ArrayBuffer` didn’t exist or I didn’t think to use it.

I’m surprised to see that there are downstream forks for npm and whatnot, but that’s pretty cool, and cooler still to hear people are actually using it!

I’d think the best option for a PR here would be letting `bytes` be any iterable, but calling `Uint8Array.from(bytes)` at the start of the hashing. This should most closely match expected behavior in C/C++ et al where you’re really just passing some pointer and a length and it’s assumed you’ve done your prep work correctly.

If that sounds good I’m happy to accept or write a PR that does just that. There shouldn’t be much of a performance overhead (if I’m still right about how `ArrayBuffer` works under the hood), and then the `inputValidation` flag is no longer needed in this “bare metal” repo. Though I think those checks are definitely good to have in your and others’ higher level libs living on npm and elsewhere.

Thanks for your work here! Also love the added example strings, though I may recommend “我的气垫船装满了鳗鱼” for the Chinese 😉.

**Comment by cimi** [comment]
Thanks for the reply! I’d be happy to open a PR here if we can avoid having to create a new major version, but I don’t how or if that’s possible.

> I’d think the best option for a PR here would be letting bytes be any iterable, but calling Uint8Array.from(bytes) at the start of the hashing. This should most closely match expected behavior in C/C++ et al where you’re really just passing some pointer and a length and it’s assumed you’ve done your prep work correctly.

I like the idea! There are a few problems though:

* [typed arrays are not available in IE/Edge](https://caniuse.com/#search=Uint8Array) so we’d need to include a fallback.
* it’ll be dangerous to use strings as input (the input length is also used for the hash, so strings of the same length will always have the same hash):
```
> Uint8Array.from("abc")
Uint8Array(3) [0, 0, 0]
```
* if the input values are not bytes and we force the conversion it can cause collisions:
```
Uint8Array.from([0, 255, 237])
> Uint8Array(3) [0, 255, 237]

Uint8Array.from([256, -1, 1773])
> Uint8Array(3) [0, 255, 237]
```

This is the reason validation is on by default in the version I published - since you get /some/ hash back even if the input has problems it’s hard for the user to tell that they might be getting wrong results. If the result is `undefined` it’s obvious that something’s wrong.

I don’t think this problem can be fixed without introducing breaking changes and having to release a new major version.

The library could detect the type of the input and do the appropriate conversion internally.

However, polyfilling this for older browsers would introduce a lot of complexity unrelated to hashing.  For example, to support strings, we’d need to include a `TextEncoder` polyfill. For performance it would also make sense to have the byte encoding as a fallback ([like here](https://jsperf.com/string-to-utf-8-bytes)), this adds even more complexity.

Even if we did this, since the output will be different in some cases if we are to match the reference, this is still a breaking change and will require releasing a new major version. I think that asking for bytes as input will give the caller a better understanding of the performance implications.

Let me know what you think!

**Comment by karanlyons** [comment]
Hey, long time no comment! I’ve had a bit of time to work on this, how does something like https://gist.github.com/karanlyons/9caf8b34445204639e42a1526f1d4743 look to you?

**Comment by karanlyons** [comment]
This is now living at the [v3-ts branch](https://github.com/karanlyons/murmurHash3.js/tree/v3-ts). I _think_ it’s fairly good to go, but I’d really appreciate it if you could look through and let me know if there’s anything I need to fix up before publishing it as a package.
